computerjazz/react-native-draggable-flatlist

README.md
`DraggableFlatList` was named inconsistently (lower case `l`) which could cause an inadvertent error.
=> Updated README.md to consistently name component

index.js
I found the issue was caused by `this._refs[index].measureInWindow` (in `measureItem` function) providing `undefined` values (x, y, width, height) to the callback.
It seems that this is related to issue [#9382](https://github.com/facebook/react-native/issues/9382) in react-native.
I resolved this issue by setting the [collapsable](https://facebook.github.io/react-native/docs/view.html#collapsable) prop on each row to `false`.
This avoids react-native 'optimization' and ensures the view exists in the view hierarchy, so that measurements can be taken.
=> bugfix: #20 - Drag-and-Drop not working on Android (RN 0.57.0)

index.js
Our rows are cards with drop shadows that get cut off by this style. 
It seems to be fine in a vertical list on iOS. I have not tested on android or with a horizontal list. Is it necessary for either of those cases?
=> Remove `overflow: hidden` from View on inside of RowItem

index.js
I am using dynamic data and I get a lot of these errors when I am filtering my data that I pass to DraggableFlatlist:
```
```
When using dynamic data on a mounted DraggableFlatlist and removing/adding items the `_refs` are not representing the current tree. Because each render will potentially remove items I suggest to clear the refs as these are anyways filled again on each render.
@fixes #17
=> clear refs on each render to avoid measurement errors

index.js
Related to #70 and maybe also #58. Container is sometimes measured before component is rendered (due to a too short setTimeout) and getting the offset wrong. I guess it should not depend on a setTimeout but rather onLayout when the component is fully rendered.
=> Measure container onLayout

index.tsx
When we have a small amount of item, like 3-4 the list don't take all the available space and is cut at the bottom on scroll.
=> Fix list cut

src/index.tsx
When passing `ItemSeparatorComponent` to the draggable FlatList I get an error stating the prop does not exist. It seems `VirtualizedListProps` doesn't have the `ItemSeparatorComponent` prop so I changed it to use `FlatListProps` instead. 
I tested the changes on locally and it cleared up the error. Let me know what you think 👍
=> Use FlatListProps instead of VirtualizedListProps

package.json, src/index.tsx, src/procs.tsx, yarn.lock
1. When trying to scroll down by dragging an item while the list is scrolled at the top, the scroll never starts
2. When trying to build the app, we get the error:
```
node_modules/react-native-reanimated/react-native-reanimated.d.ts:477:7 - error TS1254: A 'const' initializer in an ambient context must be a string or numeric literal or literal enum reference.
477   } = Animated;
~~~~~~~~
Found 1 error.
```
This was happening because:
1. `autoscroll` is called, and it calls `scrollToAsync`, which creates a promise
2. `onScroll` is called even before the scroll happens, and immediately calls `this.onAutoscrollComplete` with the current scroll position (at the top of the document) because `this.isScrolledUp` is true. This then resolves the `scrollToAsync` promise with the current document …
=> Fixed autoscroll being stuck when already scrolled to top/bottom

src/index.tsx
Allow for hitSlop to be set for the PanGestureHandler, this allows to specify "drag handles" on the side while still allowing for ScrollViev scrolling when the DraggableFlatlist is nested within a ScrollView. Also allows having a "activation toggle" but setting the hitSlop to full screen width or 0 through state variable.
=> Add hitSlop

src/index.tsx
- Fix case where use if quickly swiping using `onPressIn`
- Separated some animated values that were tracking too much into single-purpose values
- General cleanup
Fixes https://github.com/computerjazz/react-native-draggable-flatlist/issues/214
=> Fix onPressIn swipe

.gitignore, README.md, package.json, src/index.tsx, yarn.lock
This PR adds the `simultaneousHandlers` prop to the draggable list. This is used for attaching simultaneous handlers to the list's `PanGestureHandler`.
The issue that caused a containing scroll view to be unresponsive was that the gesture handler within the component was capturing the gesture before the scroll view. When we attach the scroll view reference as a simultaneous handler to the pan gesture handler, it starts working again.
For more information on cross-handler interactions, see https://docs.swmansion.com/react-native-gesture-handler/docs/interactions/.
Here is an example of how it works:
```jsx
import { ScrollView } from "react-native-gesture-handler";
import DraggableFlatList from "react-native-draggable-flatlist";
// ...
const scrollViewRef = useRef<ScrollView>(null); …
```
=> Add simultaneous handlers support to make the component usable within a ScrollView

src/index.tsx
When the draggable list is rendered in [react-native-pager-view](https://github.com/callstack/react-native-pager-view) or a `ScrollView` with `removeClippedSubviews` the list will only work on the first page.
`containerRef.getNode().measure` will return undefined for `w` and `h`, due to this when dragging an item it will go out of the list.
Heres a video of the bug:
https://user-images.githubusercontent.com/50402950/119359441-ea388680-bca9-11eb-924f-01dd5331a8a6.mp4
And heres a video after the fix:
https://user-images.githubusercontent.com/50402950/119359786-413e5b80-bcaa-11eb-8b49-7b88fceb0174.mp4
I have tested it on:
PS: I can provide the example if needed
=> fix: Bad hover offset when used in pager

src/components/DraggableFlatList.tsx
According to official react native documentation measurements are not available until after the rendering has been completed in native. https://reactnative.dev/docs/direct-manipulation#measurecallback
`Note that these measurements are not available until after the rendering has been completed in native. If you need the measurements as soon as possible and you don't need pageX and pageY, consider using the onLayout property instead`
https://reactnative.dev/docs/view#onlayout
Fixes #313
=> fixed layout measurement

src/components/DraggableFlatList.tsx
Currently, the TypeScript type of the props is basically unusable for `DraggableFlatList`, as the data will always be `unknown`. This PR is to fix the type.
=> Fixed `DraggableFlatList` generic type props

src/components/CellRendererComponent.tsx
While using the latest version of react-native-draggable-flatlist in the Wanderlog app, we ran into this error:
This points to this bit of compiled code:
```ts
var onCellLayout = react_1.useCallback(function (e) {
updateCellMeasurements();
onLayout(e);
}, [updateCellMeasurements, onLayout]);
```
Reading the React documentation on FlatList, it doesn't make any mention that `onLayout` will always be provided, and I'm guessing it isn't provided by default with the version of RN (0.64) and react-native-reanimated (2.3.1) that I"m using.
Don't call `onLayout` if it's undefined
Tested in app and verified the error is now gone
=> Fix CellRendererComponent to not error when no onLayout provided

src/types.ts
viewproptypes removed from react native 0.70+ so this library imported it but never used. This PR for version 4 beta actually. Not the RNReanimated v1 version. 
Could not figure it out the beta branch so opened for master. I can change it.
=> removed unused ViewPropTypes

src/components/DraggableFlatList.tsx
It would be helpful to call the onRelease callback in this case as well. For my particular use case I am using haptics for feedback and in this case of a user beginning a drag and not moving and then lifting their finger there was no good option for a haptic feedback. Putting the haptic on the onDragEnd has a delay which is not ideal.
=> Calling onRelease when user ends drag without moving their finger.

src/components/DraggableFlatList.tsx
onPlaceholderIndexChange functionality was removed in the recent version but the prop remained. I have added functionality in for this already existing prop.
I am not sure how this used to function but it seemed to me to only call this when the index changes from the initial position. Perhaps this is not ideal? For my use case I wanted to use a haptic "click" as an item is dragged around and listening for this change while ignoring the starting index and ending index was/is most ideal.
=> Adding onPlaceholderIndexChange callback prop functionality

src/context/animatedValueContext.tsx
The Reanimated since version 3 captures entire objects to the worklet's closure, instead of capturing just single object property. However, this can cause problems when some objects contain circular references. To avoid issues, it is highly recommended to only pass objects that are as small as possible to the worklet closure.
=> Fix circular reference with Reanimated 3

src/components/DraggableFlatList.tsx, src/context/refContext.tsx, src/hooks/useCellTranslate.tsx, src/hooks/useOnCellActiveAnimation.ts
I hit the error in #539 when using this library. The patch suggested in the issue has solved the problem for me.
Closes #539
=> Tried to modify key current of an object which has been already passed to a worklet
